Repository RedFroggy/Open3CL, pull requests merged in 2024-04, with the labels that each got.

#1 chore: add npm package description
  .gitignore
  package-lock.json
  package.json
Labels: documentation

#2 Add quality support
  .eslintrc.json
  .gitignore
  .prettierignore
  .prettierrc
  README.md
  package-lock.json
  package.json
  src/10_besoin_fr.js
  src/10_clim.js
  src/11_besoin_ecs.js
  src/11_ecs.js
  src/11_nadeq.js
  src/12.4_pac.js
  src/13.2_generateur_combustion.js
  src/13.2_generateur_combustion_ch.js
  src/13_rendement_distribution_ecs.js
  src/14_generateur_ecs.js
  src/15_conso_aux.js
  src/16_conso_eclairage.js
  src/2021_04_13_confort_ete.js
  src/2021_04_13_qualite_isolation.js
  src/3.1_b.js
  src/3.2.1_mur.js
  src/3.2.2_plancher_bas.js
  src/3.2.3_plancher_haut.js
  src/3.3.1.4_porte.js
  src/3.3_baie_vitree.js
  src/3.4_pont_thermique.js
  src/3_deperdition.js
  src/4_ventilation.js
  src/5_conso_ventilation.js
  src/6.1_apport_gratuit.js
  src/6.2_surface_sud_equivalente.js
  src/7_inertie.js
  src/8_intermittence.js
  src/9_besoin_ch.js
  src/9_chauffage.js
  src/9_conso_ch.js
  src/9_emetteur_ch.js
  src/9_generateur_ch.js
  src/apport_et_besoin.js
  src/conso.js
  src/engine.js
  src/tv.js
  src/utils.js
  test/run_one_dpe.js
  test/xml_to_json.js
Labels: documentation, enhancement

#4 ci: add github package npm registry deploy
  .github/workflows/build.yml
  .github/workflows/release.yml
  .gitignore
  package-lock.json
  package.json
Labels: enhancement

#19 chore: add contributing notice and issues templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  CONTRIBUTING.md
Labels: documentation
